version: '2'
services:
  datastore:
    image: busybox
    tty: true
    volumes:
      - /app/tmp/sockets
      - /var/lib/postgresql/data
      - /data
  db:
    image: postgres:9.6.0
    volumes_from:
      - datastore
  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"
    volumes_from:
      - datastore
  nginx:
    build:
      context: ./nginx/.
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - datastore
    depends_on:
      - web
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/unicorn.pid && bundle exec unicorn_rails -c config/unicorn.rb"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    volumes_from:
      - datastore
    depends_on:
      - db
      - redis
